In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

## Q1

In [3]:
pd.__version__ # checking pandas version

'3.0.6'

In [4]:
# intial load of dataset

df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


## Q2

In [5]:
df.shape #checking data set shape

(10000, 11)

## Q3

In [6]:
df['fuel_type'].nunique() # checking for unique values in 'fuel_type' column 

3

## Q4

In [7]:
df.isna().sum() # checking for NAN values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5

In [8]:
df[df['origin'] == 'Asia'].max() # checking maximum fuel efficiency of cars from Asia

model_year                         2024
origin                             Asia
fuel_type                        Hybrid
drivetrain             Rear-wheel drive
num_doors                             5
engine_displacement                3020
num_cylinders                         8
horsepower                        334.0
vehicle_weight                     5280
acceleration                       23.8
fuel_efficiency_mpg                41.2
dtype: object

## Q6

In [12]:
print (f'Median value of horsepower column {df['horsepower'].median()}') # checking for median value in horse power column
print (f'Mode of horsepower column {df['horsepower'].mode()}') # checking for mode in horse power column

print ('handling null values for horsepower column')
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])  # filling null values with mode
print(df['horsepower'].isna().sum())

print (f'Median value after missing value removal of horsepower column {df['horsepower'].median()}') 


Median value of horsepower column 254.0
Mode of horsepower column 0    252.0
Name: horsepower, dtype: float64
handling null values for horsepower column
0
Median value after missing value removal of horsepower column 252.0


## Q7

In [33]:
df_asia = df[df['origin'] == 'Asia']
x = np.array(df_asia[['vehicle_weight', 'model_year']].head(7))
print (x)
print (' ')
print (f'matrix-matrix multiplication {x.dot(x.T)}')
xtx = x.T.dot(x)
xtx_inverse = np.linalg.inv(xtx)
print (' ')
print (f'the inverse of xtx is {xtx_inverse}')
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print (' ')
print (xtx_inverse)
print (x.T)
result = xtx_inverse.dot(x.T)
result.dot(y).sum()


[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
 
matrix-matrix multiplication [[21961616 22250432 21921212 22688888 20753972 24173916 22897924]
 [22250432 22544164 22209324 22990376 21022444 24498332 23201348]
 [21921212 22209324 21880909 22646666 20716479 24128437 22855443]
 [22688888 22990376 22646666 23448884 21428846 24992538 23662582]
 [20753972 21022444 20716479 21428846 19630549 22818647 21629633]
 [24173916 24498332 24128437 24992538 22818647 26646941 25217899]
 [22897924 23201348 22855443 23662582 21629633 25217899 23878861]]
 
the inverse of xtx is [[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
 
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]


np.float64(0.36919696904925486)